# Common Error in Running `main.py`
- connection to api failed: you will see 404 request messages. Run again with refinitiv logged in
- upload to mongodb failed: you will see "Upload [weekly_spc] failed. (Probably due to duplicates or connection error)" 
please check if records of the same week has already been uploaded to the database.